// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDac9WfjynaoCaotz9eLWHvWTgFvRPb2QU',
    appId: '1:356196375478:web:f3ae69b7003f37003fbf17',
    messagingSenderId: '356196375478',
    projectId: 'fir-tutorials-3bd7c',
    authDomain: 'fir-tutorials-3bd7c.firebaseapp.com',
    storageBucket: 'fir-tutorials-3bd7c.appspot.com',
    measurementId: 'G-1J2MSJ8K3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnNYgZk3SN5K3r6ej1rzYqx87Nqs6p_e0',
    appId: '1:356196375478:android:f100af2c8ba10d303fbf17',
    messagingSenderId: '356196375478',
    projectId: 'fir-tutorials-3bd7c',
    storageBucket: 'fir-tutorials-3bd7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNoQnwwy4w3rcFuhcIuq54WLNJsUzZH_M',
    appId: '1:356196375478:ios:1550daf3bd0e6bb63fbf17',
    messagingSenderId: '356196375478',
    projectId: 'fir-tutorials-3bd7c',
    storageBucket: 'fir-tutorials-3bd7c.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNoQnwwy4w3rcFuhcIuq54WLNJsUzZH_M',
    appId: '1:356196375478:ios:5f635041381e20183fbf17',
    messagingSenderId: '356196375478',
    projectId: 'fir-tutorials-3bd7c',
    storageBucket: 'fir-tutorials-3bd7c.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial.RunnerTests',
  );
}
